name: Go CI

on:
  push:
    paths:
      - 'auth-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: cd auth-api && go build && go test ./...
