version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  users-api:
    build: ./users-api
    ports:
      - '8083:8083'
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083

  todos-api:
    build: ./todos-api
    ports:
      - '8082:8082'
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  auth-api:
    build: ./auth-api
    ports:
      - '8000:8000'
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083

  log-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth-api
      - todos-api
      - users-api

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "81:81"
    depends_on:
      - todos-api

