

  users-api:
    build: ./users-api
    ports:
      - '8083:8083'
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083

  todos-api:
    build: ./todos-api
    ports:
      - '8082:8082'
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  auth-api:
    build: ./auth-api
    ports:
      - '8000:8000'
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083

  log-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
