name: CI - Auth API

on:
  push:
    paths:
      - 'auth-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'

      - name: Instalar dep (gestor de dependencias)
        run: |
          go install github.com/golang/dep/cmd/dep@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Restaurar dependencias
        run: |
          cd auth-api
          $(go env GOPATH)/bin/dep ensure

      - name: Compilar Auth API
        run: cd auth-api && go build
