name: CI - Auth API

on:
  push:
    paths:
      - 'auth-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Restaurar dependencias
        run: cd auth-api && go mod tidy

      - name: Compilar Auth API
        run: cd auth-api && go build
