name: Infra Deploy

on:
  push:
    branches: [infra/master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Docker y Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Desplegar Infraestructura
        run: docker-compose -f docker-compose.dev.yml up -d
