name: Deploy to Azure VM

on:
  pull_request:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect and deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf microservice-app-example
            git clone https://github.com/Danielms111/microservice-app-example.git
            cd microservice-app-example
            git pull origin master
            sudo docker-compose -f docker-compose.dev.yml down
            sudo docker-compose -f docker-compose.dev.yml up -d --build
