name: Infra Deploy

on:
  pull_request:
    branches:
      - infra/master
      - infra/dev
    paths:
      - 'docker-compose.dev.yml'
      - '.github/workflows/infra.yml'

  push:
    branches:
      - infra/feature/**
      - infra/hotfix/**
    paths:
      - 'docker-compose.dev.yml'
      - '.github/workflows/infra.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Docker y Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Desplegar Infraestructura
        run: docker-compose -f docker-compose.dev.yml up -d
