name: Build & Test Spring Boot App

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'users-api/**'

  push:
    branches:
      - feature/**
      - hotfix/**
    paths:
      - 'users-api/**'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven (skip tests)
        run: mvn -B clean package -DskipTests --file users-api/pom.xml

